name: build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the arm64 image
        run: |
          docker buildx build --push \
            --tag gpoleze/pms:latest \
            --tag gpoleze/pms:$RELEASE_VERSION \
            --platform linux/arm64 \
            -f Dockerfile.arm64 .
      - name: build the adm64 image
        run: |
          docker buildx build --push \
            --tag gpoleze/pms:latest \
            --tag gpoleze/pms:$RELEASE_VERSION \
            --platform linux/amd64 \
            -f Dockerfile .