name: build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Envs
      - name: Set env
        run: echo "RELEASE_VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      # Actions
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the arm64 image
        run: |
          docker buildx build --push \
            --tag gpoleze/pms:latest \
            --tag gpoleze/pms:$RELEASE_VERSION \
            --platform linux/arm64 \
            -f Dockerfile.arm64 .
      - name: build the adm64 image
        run: |
          docker buildx build --push \
            --tag gpoleze/pms:latest \
            --tag gpoleze/pms:$RELEASE_VERSION \
            --platform linux/amd64 \
            -f Dockerfile .